# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd))

trigger:
- master

queue:
  name: Hosted VS2017

steps:
- powershell: .\bootstrap.ps1
  displayName: 'Install pre-requisites'
  
- powershell: Invoke-Build -Configuration 'Production' -Task Clean, CopyModuleFiles, PublishModule
  displayName: 'Publish PowerShell Module'
  env:
    psgallery: $(NugetAPIKey)
